# Generated by Django 4.2.2 on 2023-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2023-06-16 12:34:56'),
            preserve_default=False,
        ),
    ]
